version: "3.8"
services:
  app:
    container_name: benggri-github-io
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    network_mode: host